### ISSUE TITLE
Расширение примера до сети launchpadов

### ISSUE THREAD

**Issue by nanshakov** [vostok-project/launchpad#10]
Я хочу посмотреть трассировки в более "боевом режиме", эмулировав ситуацию с несколькими микросервисами. Я понимаю, что можно из одного  launchpadа отправить запрос (например post) в такой же launchpad. Нужно ли передавать вручную traceId или что то еще ? Хотелось бы иметь более жизненный пример из коробки, но понимаю что вам сейчас не до этого.

**Comment by beevee** [comment]
Эта идея хорошая, мы сделаем что-то такое в будущем. Пока что можно сгенерировать два приложения ланчпадом и делать запросы от одного к другому с помощью ClusterClient. Все необходимые идентификаторы будут прокидываться сами собой.
