### ISSUE TITLE
Отсутствует валидация на имя проекта при генерации

### ISSUE THREAD

**Issue by xoposhiy** [vostok-project/launchpad#3]
`launchpad -n super-project` успешно работает, но генерирует некомпилирующийся проект, потому что генерирует namespace super-project — что некорректно, потому что в имени namespace не может быть дефисов.

Ещё не очевидно, что имя проекта должно соответствовать стилю именования пространств имён.
Может быть лучше его спрашивать не параметром exe-шника, а из консоли после соответствующего пояснения. Подобным образом ведёт себя npm, например.

**Comment by trurl123** [comment]
поправлено
