### ISSUE TITLE
dotnet restore использует выключенные источники nuget пакетов

### ISSUE THREAD

**Issue by xoposhiy** [vostok-project/launchpad#4]
Как следствие, launchpad не работает, сгенерированный проект не собирается.

Выглядит как будто это ошибка в dotnet. 

Воспроизведется у всех, у кого настроен внутриконтуровский источник nuget-пакетов, а ланчпадом они пытаются пользоваться из-вне контуровской сети, выключив (но не удалив) предварительно внутриконтуровский источник.

Мой %AppData%\Nuget\Nuget.config (см disabledPackageSources):

```
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="kontur" value="http://nuget/api/v2" />
  </packageSources>
  <disabledPackageSources>
    <add key="kontur" value="true" />
  </disabledPackageSources>
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
  <bindingRedirects>
    <add key="skip" value="False" />
  </bindingRedirects>
  <packageManagement>
    <add key="format" value="0" />
    <add key="disabled" value="False" />
  </packageManagement>
</configuration>
```

**Comment by AndrewKostousov** [comment]
Похоже, это оно - https://github.com/NuGet/Home/issues/5704.

Решение - использовать свежие тулы, в частности nuget.exe >= v4.3.0

Паша @xoposhiy, можешь подтвердить, что после обновления VS2017 до последней версии ошибка пропадает?

**Comment by trurl123** [comment]
поправлен баг с восстановлением пакетов, надо перепроверить
