### ISSUE TITLE
Rename Launchpad executable

### ISSUE THREAD

**Issue by igorlukanin** [vostok-project/launchpad#5]
I propose that Vostok CLI executable should be named `vostok` instead of `launchpad`.

Then Launchpad will be available as `vostok launchpad ...` or maybe `vostok create ...`.

Future functions will get their own *subnames* and will be available as `vostok subname ...`.

**Comment by beevee** [comment]
I definitely agree that we need to add subnames for different functions, even if there is only one available now.

On renaming to `vostok`, I'm not sure.

CC @AndrewKostousov @spaceorc @trurl123 @Pliner @iloktionov @ezsilmar

**Comment by beevee** [comment]
So, I'll make:

`$ ./launchpad.sh create --name TestProject`

instead of:

`$ ./launchpad.sh --name TestProject`

And I need second opinion on renaming.

**Comment by igorlukanin** [comment]
On my macOS box, there're 2 executables starting with "launch", and none starting with "vo". So if we stick with `launchpad`, we'll have to type "launchp" + TAB. If we go with "vostok", we'll have to type "vo" + TAB only.

<img width="822" alt="screen shot 2017-10-19 at 14 24 31" src="https://user-images.githubusercontent.com/3852894/31764049-7ff8608c-b4d9-11e7-97a4-d0d54ce095d1.png">

It's also better for branding (but I'm neither sure, nor can prove that).

**Comment by AndrewKostousov** [comment]
+1 for renaming launchpad -> vostok

**Comment by beevee** [comment]
Please, take a look at #6.
