### ISSUE TITLE
Server returns local Spaceport trace URL instead of a "traceId"

### ISSUE THREAD

**Issue by igorlukanin** [vostok-project/launchpad#9]
Expected:

```
{
    "traceId": "bedfdf88-704d-493f-a458-2999d0b57e09",
    "url": "http://localhost:33333/"
}
```

Got:

```
{
    "traceId": "http://localhost:6301/bedfdf88-704d-493f-a458-2999d0b57e09",
    "url": "http://localhost:33333/"
}
```

**Comment by trurl123** [comment]
Слишком мало информации, какой сервер, при чем тут ланчпад? Откуда получено, почему это ожидается?

**Comment by igorlukanin** [comment]
Андрей, если с помощью Launchpad создать приложение по шаблону, запустить его и отправить к нему GET-запрос на /, то будет ответ, как во втором сниппете. Там URL, хотя название поля говорит, что будет traceId. Ответ должен быть, как в первом сниппете. Я обсуждал это с @beevee.

**Comment by trurl123** [comment]
можно пример этого приложения?

**Comment by igorlukanin** [comment]
Да, конечно! Запусти на своей машине:

```
./vostok.cmd create --name TestProject
```
